name: Create Release

env:
  GITHUB_TOKEN: ${{ secrets.token }}

on:
  push:
    branches:
      - main

jobs:
  version:
    uses: ./.github/workflows/task-version.yml

  artifact:
    uses: ./.github/workflows/task-artifact.yml

  release:
    needs:
      - artifact
      - version
    uses: ./.github/workflows/task-release.yml
    with:
      version: ${{ needs.version.outputs.version_output }}
      prerelease: false
  
  build:
    runs-on: ubuntu-latest
    steps:

        
      - name: Archive Release for application
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'filemanager-${{ steps.version.outputs.version }}.zip'
          exclusions: '*.git* *.idea* *.github* /*var/* .editorconfig'
          directory: .

      - name: Create new Release with semantic-version tag
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          name: Release ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}
          artifacts: filemanager-${{ steps.version.outputs.version }}.zip
          artifactContentType: application/zip
          bodyFile: RELEASE_NOTE.md

  docker_image:
    needs:
      - version
    uses: ./.github/workflows/task-docker.yml
    with:
      reponame: 'git.h2-invent.com/filemanager/application'
      dockerfile_path: './Dockerfile'
      directory: '.'
      version: ${{ needs.version.outputs.version_output }}
      tags: git.h2-invent.com/filemanager/application:${{ needs.version.outputs.version_output }},git.h2-invent.com/filemanager/application:latest
    secrets:
      docker_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
