name: Create Release

env:
  GITHUB_TOKEN: ${{ secrets.token }}

on:
  push:
    branches:
      - main

jobs:
  version:
    uses: ./.github/workflows/task-version.yml

  artifact:
    uses: ./.github/workflows/task-artifact.yml

  release:
    needs:
      - artifact
      - version
    uses: ./.github/workflows/task-release.yml
    with:
      version: ${{ needs.version.outputs.version_output }}
      prerelease: false

  docker_image:
    needs:
      - version
    uses: ./.github/workflows/task-docker.yml
    with:
      reponame: 'git.h2-invent.com/filemanager/application'
      dockerfile_path: './Dockerfile'
      directory: '.'
      version: ${{ needs.version.outputs.version_output }}
      tags: git.h2-invent.com/filemanager/application:${{ needs.version.outputs.version_output }},git.h2-invent.com/filemanager/application:latest
    secrets:
      docker_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
