name: Create Release

env:
  GITHUB_TOKEN: ${{ secrets.token }}

on:
  push:
    branches:
      - main

jobs:
  version:
    uses: ./.github/workflows/task-version.yml

  docker_image:
    needs:
      - version
    uses: ./.github/workflows/task-docker.yml
    with:
      repository: reg.h2-invent.com
      dockerfile_path: './Dockerfile'
      directory: '.'
      version: ${{ needs.version.outputs.version_output }}
      tags: reg.h2-invent.com/filemanager/core:${{ needs.version.outputs.version_output }},reg.h2-invent.com/filemanager/core:latest
    secrets:
      docker_password: ${{ secrets.HARBOR_PUSH_PASSWORD }}
      docker_username: ${{ secrets.HARBOR_PUSH_USERNAME }}
