name: Build Artifacts

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update PHP Version and tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          ini-values: date.timezone ="Europe/Berlin"
          extensions: gd,intl,mbstring

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: "--optimize-autoloader"
