name: Release Version

on:
  workflow_call:
    inputs:
      version:
        description: 'release version'
        default: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create new Release with semantic-version tag
        uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: false
          name: Release ${{ inputs.version }}
          tag: ${{ inputs.version }}
          bodyFile: RELEASE_NOTE.md
